# Generated by Django 3.2 on 2021-10-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washers', '0002_booking_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='car_no',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='booking_details',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
